### ISSUE TITLE
Crashes when breaking tile entities

### ISSUE THREAD

**Issue by Mirsario** [Eng1N33R/MechanicalTech#11]
I encounter the following crash whenever I break a manual crank, or a water wheel. If it matters at all, they were both in water. This was on `fabric-loader-0.10.8-1.16.4`, version 0.2.0 of the mod.

[crash-2020-12-19_01.15.38-client.txt](https://github.com/Eng1N33R/MechanicalTech/files/5718349/crash-2020-12-19_01.15.38-client.txt)

**Comment by Mirsario** [comment]
~~Hmm, this actually seems to be a conflict with OptiFabric + Optifine.~~

**Comment by Mirsario** [comment]
I believe that updating fabric API mod fixed this conflict for me, These are the version I used:
![image](https://user-images.githubusercontent.com/6795251/102695314-8829b000-4237-11eb-9f4c-9c22023fe7b6.png)
Raise the minimal version number perhaps?

**Comment by Mirsario** [comment]
..No, it isn't. The following crash log does not have it enabled.

[crash-2020-12-19_20.39.50-client.txt](https://github.com/Eng1N33R/MechanicalTech/files/5719914/crash-2020-12-19_20.39.50-client.txt)

> After some googling, and running into a similar crash in another mod - it seems like something's just missing BlockState.isAir() checks somewhere, or the block entities don't get removed in time.

**Comment by oOHiyoriOo** [comment]
(Bump) got the same error today when breaking tiles:
`Cannot get property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} as it does not exist in Block{minecraft:air}`

Using Fabric Optifine btw!

**Comment by oOHiyoriOo** [comment]
got it only using this and optifine (i would really love to use optifine :( )
![image](https://user-images.githubusercontent.com/44544317/107425724-a0bf9380-6b1f-11eb-8999-7ffbd4e36223.png)

**Comment by Mirsario** [comment]
As I said prior, this has nothing to do with optifine, and is reproducible without it.
