### ISSUE TITLE
[Feature Request] Machine recipe integration with REI

### ISSUE THREAD

**Issue by JoelZBub** [Eng1N33R/MechanicalTech#14]
When using REI to find recipes, there are no recipes for the input and output of MechanicalTech machines. 
If I look at wheat flour, for instance, you can see that it can be used in a vanilla furnace to make bread, but there is no recipe or tab that shows that you obtain wheat flour thru the mill. (See screenshots below)

I would like a recipe tab in REI that shows the recipes for each MechanicalTech machine, just as there is for each vanilla tile that has a recipe.
Additionally, vanilla blocks such as the furnace, if you right click them, show all the recipes that are registered to that block. (see screenshot below) This behavior should be included in MechanicalTech machines as well.

Screenshots:
![2020-12-29_08 30 29](https://user-images.githubusercontent.com/12024500/103287272-1fb59e00-49b0-11eb-9efe-21597b061726.png)
![2020-12-29_08 26 47](https://user-images.githubusercontent.com/12024500/103287282-22b08e80-49b0-11eb-8386-e67a3baa8f61.png)

**Comment by EngiN33R** [comment]
Thank you for commenting on this oversight! This functionality has been added to the upcoming release.
